### ISSUE TITLE
Publish the index of the waypoint of the nearest upcoming red light's stop line on /traffic_waypoint

### ISSUE THREAD

**Issue by knight-riders** [knight-riders/CarND-Capstone-Project#17]
For example, if waypoints is the complete list of waypoints, and an upcoming red light's stop line is nearest to waypoints[12], then 12 should be published /traffic_waypoint. This index can later be used by the waypoint updater node to set the target velocity for waypoints[12] to 0 and smoothly decrease the vehicle velocity in the waypoints leading up to waypoints[12].

Can be done without a traffic light classifier, since the traffic light state ground truth is published from the simulator.

**Comment by patrickmpoon** [comment]
According to https://classroom.udacity.com/nanodegrees/nd013/parts/6047fe34-d93c-4f50-8336-b70ef10cb4b2/modules/e1a23b06-329a-4684-a717-ad476f0d8dff/lessons/462c933d-9f24-42d3-8bdc-a08a5fc866e4/concepts/d58e2c6a-1fd2-4e33-8912-861051ab301b, /traffic_waypoint publishes the index value for the nearest traffic light.

Finding the nearest traffic stop line should be a trivial task.

**Comment by patrickmpoon** [comment]
To test, insert state = TrafficLight.RED above https://github.com/knight-riders/CarND-Capstone-Project/blob/master/ros/src/tl_detector/tl_detector.py#L89. Fire off the launch file and rostopic echo /traffic_waypoint. You should get the index number of the traffic light ahead.

**Comment by knight-riders** [comment]
Hi, I reviewed your code. First, I pushed slight modifications to it in order improve our control on the resource usage of the node. Second, there is a couple of things you will need to review. The number published on /traffic_waypoint needs to be the "index of the waypoint closes to the upcoming stop line for a traffic light". The number that is published right now, is the index of the traffic_light from the /vehicle/traffic_lights topic witch won't be useful for our planner. It needs to point to a waypoint inside /base_waypoints in order for the planner to generate a /final_waypoint list with a decelerating speed setpoint up until the stop line.  Second I think you should narrow your search of a traffic light to a narrow set of upcoming waypoints. Something like 100-150 in the simulation and maybe less for the real life test say : 30. There is no need to process all the 11000 simulation waypoints (61 in real life).  Another advantage is that the traffic light classifier doesn't need to be active every step of the way. This reduces the chances of getting a false positive red light detection from the classifier.
