### ISSUE TITLE
Implement an object detection pipeline in ROS

### ISSUE THREAD

**Issue by knight-riders** [knight-riders/CarND-Capstone-Project#5]
Inside Traffic Detection Node

https://github.com/tensorflow/models/tree/master/research/object_detection
https://medium.com/@WuStangDan/step-by-step-tensorflow-object-detection-api-tutorial-part-5-saving-and-deploying-a-model-8d51f56dbcf1
https://becominghuman.ai/traffic-light-detection-tensorflow-api-c75fdbadac62

Ideas:
Create tensorflow's session out of the loop (on node init?)
Remap the simulator topic to the real camera feed when launching with site.launch

Requirements:
TensorFlow v1.3, Keras v2.0.8 + Cuda 8 + Cudnn 6.0

**Comment by patrickmpoon** [comment]
To test, insert `state = TrafficLight.RED` above https://github.com/knight-riders/CarND-Capstone-Project/blob/master/ros/src/tl_detector/tl_detector.py#L89.  Fire off the launch file and `rostopic echo /traffic_waypoint`.  You should get the index number of the traffic light ahead.
